apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T12:11:13Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "12160"
  uid: f8e3b9b3-09b6-46b3-8322-9a9d67551f23
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.224.160
  clusterIPs:
  - 10.109.224.160
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30278
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
